version: '3.9'

services:
  db:
    # image: mysql:5.6.50
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    # image: phpmyadmin
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin
    restart: always
    ports:
      - 3030:80
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=1234
      - UPLOAD_LIMIT=300M